### ISSUE TITLE
JSONstat() returns multiple datasets

### ISSUE THREAD

**Issue by maferra** [badosa/JSON-stat#17]
First, thank you very much for this library and schema. The following code should be straightforward. It gets a json response using the .getJson() from jQuery and parses the object with JSONstat().

But, why does JSONstat() returns 6 datasets instead of 1? And why are they equal? (the dataset has 6 dimensions, but, is it related with having 6 datasets?)

```
$(function() {
	console.log("Ready!");

	var filtro = { unit: "PC_ACT", s_adj: "SA" };

	$.getJSON(
		"http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/une_rt_m",
		filtro,
		function(data) {
			console.log(data);

			var x = JSONstat(data).Dataset(0);
			var y = JSONstat(data).Dataset(1);
			var z = JSONstat(data).Dataset(2);

			console.log(JSON.stringify(x) === JSON.stringify(y));

			console.log(x);
			console.log(y);
			console.log(z);
		}
	);
});
```

Best regards,

**Comment by badosa** [comment]
Actually, JSONstat in your example does not return 6 datasets. The API doc is probably not ultra-clear but here are the relevant parts:

[JSONstat()](https://github.com/badosa/JSON-stat/wiki/API-Reference#jsonstat): 

> The public properties of the jsonstat instance depend on the value of the class property.

[length](https://github.com/badosa/JSON-stat/wiki/API-Reference#length):

> Number of datasets, dimensions, categories, category children or items.

Translation: *length* meaning depends on the value of *class*. In your example, `JSONstat(data).class` returns "dataset". The length of a dataset is the number of dimensions (the lenght of a collection is the number of items, the length of a bundle is the number of datasets, the length of a dimension is the number of categories of the dimension).

Because `JSONstat(data)` is already a dataset, there's no need to `JSONstat(data).Dataset(x)`: Dataset(x) does nothing when applied to a dataset. If `JSONstat(data).class` is "dataset", `JSONstat(data).Dataset(3000)` is the same as `JSONstat(data)` because in such case `Dataset()` is simply ignored.
