### ISSUE TITLE
Optional "unit" is mandatory for "metric" dimensions in JSON_stat Explorer

### ISSUE THREAD

**Issue by djuptank** [badosa/JSON-stat#19]
Spent some time troubleshooting before finding this one.
When a dimension "role" is "meric" the JSON-Stat requires "unit" to be defined in that dimension or it fails. The structure below follows JSON-stat schema.
According to standard and Schema the "unit" should be optional. Seen on 0.13.8 and 0.13.3.

 Will fail:
{
  "version": "2.0",
  "class": "dataset",
  "label": "2019-08-28",
  "id": [
    "datetime",
    "concept"
  ],
  "size": [
    1,
    1
  ],
  "role": {
    "time": [
      "datetime"
    ],
    "metric": [
      "concept"
    ]
  },
  "value": [
    500
  ],
  "dimension": {
    "datetime": {
      "label": "datetime",
      "category": {
        "index": [
          "2019-07-16T00:00:00+02:00"
        ]
      }
    },
    "concept": {
      "label": "concept",
      "category": {
        "index": [
          "Bla_Attempt"
        ]
      }
    }
  }
}

**Comment by badosa** [comment]
You are absolutely right! This is not an issue of the JSON-stat Javascript Toolkit in itself (0.13.*) but of the JSON-stat Explorer (0.2.0). Thanks for spotting the problem!

**Comment by badosa** [comment]
> This is not an issue of the JSON-stat Javascript Toolkit in itself (0.13.*) but of the JSON-stat Explorer (0.2.0).

To be more accurate, the problem arises because the JSON-stat Javascript Toolkit's [toTable()](https://github.com/badosa/JSON-stat/wiki/API-Reference#totable) method is always invoked with "unit" *true* in the JSON-stat Explorer

https://github.com/badosa/JSON-stat/blob/d981972aa1042d588c025553458e7dbc08eb050d/explorer/src/components/Dataset.js#L54

The issue can be solved by updating the JSON-stat Explorer to conditionally invoke toTable() with different "unit" values, or by making the JSON-stat Javascript Toolkit's toTable() smarter (ignoring "unit" when there's no unit information in the dataset).

I'm pondering both solutions: I'll probably take the second route even though, technically, the Explorer is the one misbehaving, not the Toolkit.

**Comment by badosa** [comment]
Version 0.2.2 of the JSON-stat Explorer addresses the issue by requiring version 0.13.9 of the JSON-stat Javascript Toolkit.
