### ISSUE TITLE
JSONstat()

### ISSUE THREAD

**Issue by ev1stensberg** [badosa/JSON-stat#9]
Hi! Dunno if this is just me being dumb with stat, or if this is an error, but I've imported the module from npm, and tried to find values when retrieving the url. 

Could you elaborate? 

![skjermbilde 2016-08-18 kl 20 42 22](https://cloud.githubusercontent.com/assets/16735925/17786301/748a085e-6584-11e6-9446-6a656b65219a.png)
![skjermbilde 2016-08-18 kl 20 43 57](https://cloud.githubusercontent.com/assets/16735925/17786313/8185a950-6584-11e6-8106-40238f9a26c8.png)

**Comment by badosa** [comment]
The JSONstat Javascript Toolkit includes a simple XHR implementation (sync and async). It is not recommended to use such simple implementation in production and it is provided mainly for testing purposes.

The JSONstat module **does not** include such XHR implementation because node.js already comes with a built-in _http_ module and many third-party modules already try to simplify such task (like _request_ or _got_).

It is not you being dumb: it's bad documentation (my fault). This limitation is mentioned in the wiki under _Installation_ (probably an unexpected place):

https://github.com/badosa/JSON-stat/wiki/Installation

but not on NPM (that imports the JJT readme file from GitHub and it's not module-specific).

> This module has all the functionality of the client version except the connection capabilities (JSONstat accepts only a JSON-stat response object, not a URI string). Use Node.js’s built-in http module, or a module with a similar functionality (like got) to retrieve a remote JSON-stat response. See nodejs.js or our Tonic + npm code as an example.

**Comment by ev1stensberg** [comment]
Yeah! Figured it out eventually! Would be nice of some example repos, not just <script> tags in an html :) also,  an polyfill with fetch so you could call response.jsonStat() would be awesome!

**Comment by badosa** [comment]
The Readme file and the API reference have been edited to reflect the module limitations. Changes won't show on NPM until a new version is published.

**Comment by ev1stensberg** [comment]
Awesome, keep up the good work. This library has potential :)

**Comment by ev1stensberg** [comment]
Let me know if you want some help on documentation and examples with other libraries 📫
